<a href="https://colab.research.google.com/github/ThousandAI/Application-of-AI/blob/main/class01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0.4371, 0.1499, 0.2478],
        [0.3363, 0.9650, 0.6333]])
Matrix:
 [[0.19804326 0.91745895 0.66919999]
 [0.30951929 0.90015687 0.38313896]]


In [ ]:
tensor = torch.zeros(2,3)
matrix = np.zeros((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
tensor = torch.ones(2,3)
matrix = np.ones((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(f"Tensor:\n {tensor.dtype}")
print(f"Matrix:\n {matrix.dtype}")

Tensor:
 torch.float32
Matrix:
 float64


In [ ]:
print(f"Tensor:\n {tensor.size()}")
print(f"Tensor:\n {tensor.shape}")
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([2, 3])
Tensor:
 torch.Size([2, 3])
Matrix:
 (2, 3)


In [ ]:
# list to torch
tensor = torch.tensor([2.3, 1.2, 5.7])
print(f"Tensor:\n {tensor.size()}")

# list to numpy
matrix = np.array([2.3, 1.2, 5.7])
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([3])
Matrix:
 (3,)


In [ ]:
# numpy <=> torch
tensor = torch.tensor([1, 2, 3])
matrix = np.array([1, 2, 3])
print(torch.from_numpy(matrix))
print(tensor.numpy())

tensor([1, 2, 3])
[1 2 3]


In [ ]:
# call by reference
tensor = torch.tensor([1, 2, 3])
matrix = tensor.numpy()

tensor += 1
print(tensor)
print(matrix)

tensor([2, 3, 4])
[2 3 4]


In [ ]:
# operator 
t1 = torch.tensor([2.3, 1.2, 5.7])
t2 = torch.tensor([3.2, 2.8, 7.8])
print(torch.add(t1, t2)) # t1 + t2
print(torch.sub(t1, t2)) # t1 - t2
print(torch.mul(t1, t2)) # t1 * t2
print(torch.div(t1, t2)) # t1 / t2

tensor([ 5.5000,  4.0000, 13.5000])
tensor([-0.9000, -1.6000, -2.1000])
tensor([ 7.3600,  3.3600, 44.4600])
tensor([0.7188, 0.4286, 0.7308])


In [ ]:
# slice
tensor = torch.rand(5,3)
print(tensor)
print(tensor[:,1:3])
print(tensor[1,1].item())

tensor([[0.5267, 0.2479, 0.2692],
        [0.1152, 0.4911, 0.7869],
        [0.9986, 0.3048, 0.3148],
        [0.6031, 0.2052, 0.8379],
        [0.7379, 0.5874, 0.0590]])
tensor([[0.2479, 0.2692],
        [0.4911, 0.7869],
        [0.3048, 0.3148],
        [0.2052, 0.8379],
        [0.5874, 0.0590]])
0.49110180139541626


In [ ]:
# view
tensor = torch.rand(2,6)
print(tensor)
print(tensor.view(3,4))
print(tensor.view(12))
print(tensor.view(12,1))
print(tensor.view(1,12))
print(tensor.view(-1,3))

tensor([[0.1375, 0.0369, 0.5374, 0.3004, 0.2542, 0.6634],
        [0.0347, 0.0234, 0.9734, 0.7682, 0.7682, 0.0929]])
tensor([[0.1375, 0.0369, 0.5374, 0.3004],
        [0.2542, 0.6634, 0.0347, 0.0234],
        [0.9734, 0.7682, 0.7682, 0.0929]])
tensor([0.1375, 0.0369, 0.5374, 0.3004, 0.2542, 0.6634, 0.0347, 0.0234, 0.9734,
        0.7682, 0.7682, 0.0929])
tensor([[0.1375],
        [0.0369],
        [0.5374],
        [0.3004],
        [0.2542],
        [0.6634],
        [0.0347],
        [0.0234],
        [0.9734],
        [0.7682],
        [0.7682],
        [0.0929]])
tensor([[0.1375, 0.0369, 0.5374, 0.3004, 0.2542, 0.6634, 0.0347, 0.0234, 0.9734,
         0.7682, 0.7682, 0.0929]])
tensor([[0.1375, 0.0369, 0.5374],
        [0.3004, 0.2542, 0.6634],
        [0.0347, 0.0234, 0.9734],
        [0.7682, 0.7682, 0.0929]])
