<a href="https://colab.research.google.com/github/ThousandAI/AI-DeepLearning/blob/main/class01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

In [ ]:
import torch
import numpy as np

In [ ]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0.5854, 0.3711, 0.8838],
        [0.4893, 0.6822, 0.8711]])
Matrix:
 [[0.7391614  0.72220692 0.93697072]
 [0.52557138 0.75350283 0.28772291]]


In [ ]:
tensor = torch.zeros(2,3)
matrix = np.zeros((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
tensor = torch.ones(2,3)
matrix = np.ones((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(f"Tensor:\n {tensor.dtype}")
print(f"Matrix:\n {matrix.dtype}")

Tensor:
 torch.float32
Matrix:
 float64


In [ ]:
print(f"Tensor:\n {tensor.size()}")
print(f"Tensor:\n {tensor.shape}")
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([2, 3])
Tensor:
 torch.Size([2, 3])
Matrix:
 (2, 3)


In [ ]:
# list to torch
tensor = torch.tensor([2.3, 1.2, 5.7])
print(f"Tensor:\n {tensor.size()}")

# list to numpy
matrix = np.array([2.3, 1.2, 5.7])
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([3])
Matrix:
 (3,)


In [ ]:
# numpy <=> torch
tensor = torch.tensor([1, 2, 3])
matrix = np.array([1, 2, 3])
print(torch.from_numpy(matrix))
print(tensor.numpy())

tensor([1, 2, 3])
[1 2 3]


In [ ]:
# call by reference
tensor = torch.tensor([1, 2, 3])
matrix = tensor.numpy()

tensor += 1
print(tensor)
print(matrix)

tensor([2, 3, 4])
[2 3 4]


In [ ]:
# operator
t1 = torch.tensor([2.3, 1.2, 5.7])
t2 = torch.tensor([3.2, 2.8, 7.8])
print(torch.add(t1, t2)) # t1 + t2
print(torch.sub(t1, t2)) # t1 - t2
print(torch.mul(t1, t2)) # t1 * t2
print(torch.div(t1, t2)) # t1 / t2

tensor([ 5.5000,  4.0000, 13.5000])
tensor([-0.9000, -1.6000, -2.1000])
tensor([ 7.3600,  3.3600, 44.4600])
tensor([0.7188, 0.4286, 0.7308])


In [ ]:
# slice
tensor = torch.rand(5,3)
print(tensor)
print(tensor[:,1:3])
print(tensor[1,1])
print(tensor[1,1].item())

tensor([[0.6576, 0.4436, 0.0234],
        [0.8745, 0.3603, 0.9149],
        [0.3180, 0.5381, 0.9160],
        [0.6178, 0.7811, 0.8106],
        [0.1372, 0.0591, 0.9106]])
tensor([[0.4436, 0.0234],
        [0.3603, 0.9149],
        [0.5381, 0.9160],
        [0.7811, 0.8106],
        [0.0591, 0.9106]])
tensor(0.3603)
0.36032527685165405


In [ ]:
# view
tensor = torch.rand(2,6)
print(tensor)
print(tensor.view(3,4))
print(tensor.view(12))
print(tensor.view(12,1))
print(tensor.view(1,12))
print(tensor.view(-1,3))

tensor([[0.7930, 0.3077, 0.6974, 0.5426, 0.7451, 0.0156],
        [0.5863, 0.3621, 0.1844, 0.5733, 0.9587, 0.2368]])
tensor([[0.7930, 0.3077, 0.6974, 0.5426],
        [0.7451, 0.0156, 0.5863, 0.3621],
        [0.1844, 0.5733, 0.9587, 0.2368]])
tensor([0.7930, 0.3077, 0.6974, 0.5426, 0.7451, 0.0156, 0.5863, 0.3621, 0.1844,
        0.5733, 0.9587, 0.2368])
tensor([[0.7930],
        [0.3077],
        [0.6974],
        [0.5426],
        [0.7451],
        [0.0156],
        [0.5863],
        [0.3621],
        [0.1844],
        [0.5733],
        [0.9587],
        [0.2368]])
tensor([[0.7930, 0.3077, 0.6974, 0.5426, 0.7451, 0.0156, 0.5863, 0.3621, 0.1844,
         0.5733, 0.9587, 0.2368]])
tensor([[0.7930, 0.3077, 0.6974],
        [0.5426, 0.7451, 0.0156],
        [0.5863, 0.3621, 0.1844],
        [0.5733, 0.9587, 0.2368]])


In [ ]:
# GPU
print(torch.cuda.is_available())
# if torch.cuda.is_available():
#   device = torch.device("cuda")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(3,2).to(device)

print(x)
x = x.to("cpu")
print(x)

True
tensor([[0.0190, 0.9373],
        [0.9444, 0.4690],
        [0.7684, 0.6871]], device='cuda:0')
tensor([[0.0190, 0.9373],
        [0.9444, 0.4690],
        [0.7684, 0.6871]])
