<a href="https://colab.research.google.com/github/ThousandAI/Application-of-AI/blob/main/class01/class01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[7.9238e-01, 2.1184e-01, 6.4969e-05],
        [3.8380e-02, 4.0757e-01, 8.9598e-01]])
Matrix:
 [[0.936506   0.23812525 0.53562868]
 [0.50217936 0.23938692 0.60093513]]


In [3]:
tensor = torch.zeros(2,3)
matrix = np.zeros((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
tensor = torch.ones(2,3)
matrix = np.ones((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(f"Tensor:\n {tensor.dtype}")
print(f"Matrix:\n {matrix.dtype}")

Tensor:
 torch.float32
Matrix:
 float64


In [6]:
print(f"Tensor:\n {tensor.size()}")
print(f"Tensor:\n {tensor.shape}")
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([2, 3])
Tensor:
 torch.Size([2, 3])
Matrix:
 (2, 3)


In [7]:
# list to torch
tensor = torch.tensor([2.3, 1.2, 5.7])
print(f"Tensor:\n {tensor.size()}")

# list to numpy
matrix = np.array([2.3, 1.2, 5.7])
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([3])
Matrix:
 (3,)


In [8]:
# numpy <=> torch
tensor = torch.tensor([1, 2, 3])
matrix = np.array([1, 2, 3])
print(torch.from_numpy(matrix))
print(tensor.numpy())

tensor([1, 2, 3])
[1 2 3]


In [9]:
# call by reference
tensor = torch.tensor([1, 2, 3])
matrix = tensor.numpy()

tensor += 1
print(tensor)
print(matrix)

tensor([2, 3, 4])
[2 3 4]


In [10]:
# operator 
t1 = torch.tensor([2.3, 1.2, 5.7])
t2 = torch.tensor([3.2, 2.8, 7.8])
print(torch.add(t1, t2)) # t1 + t2
print(torch.add(t1, t2)) # t1 - t2
print(torch.mul(t1, t2)) # t1 * t2
print(torch.div(t1, t2)) # t1 / t2

tensor([ 5.5000,  4.0000, 13.5000])
tensor([ 5.5000,  4.0000, 13.5000])
tensor([ 7.3600,  3.3600, 44.4600])
tensor([0.7188, 0.4286, 0.7308])


In [11]:
# slice
tensor = torch.rand(5,3)
print(tensor)
print(tensor[:,1:3])
print(tensor[1,1].item())

tensor([[0.0975, 0.4026, 0.7074],
        [0.1463, 0.7168, 0.7415],
        [0.1243, 0.0133, 0.6769],
        [0.5864, 0.7550, 0.0732],
        [0.3886, 0.4852, 0.3933]])
tensor([[0.4026, 0.7074],
        [0.7168, 0.7415],
        [0.0133, 0.6769],
        [0.7550, 0.0732],
        [0.4852, 0.3933]])
0.716823399066925


In [12]:
# view
tensor = torch.rand(2,6)
print(tensor)
print(tensor.view(3,4))
print(tensor.view(12))
print(tensor.view(12,1))
print(tensor.view(1,12))
print(tensor.view(-1,3))

tensor([[0.9594, 0.3548, 0.9751, 0.5854, 0.6431, 0.8459],
        [0.8374, 0.4420, 0.2574, 0.1708, 0.4292, 0.1682]])
tensor([[0.9594, 0.3548, 0.9751, 0.5854],
        [0.6431, 0.8459, 0.8374, 0.4420],
        [0.2574, 0.1708, 0.4292, 0.1682]])
tensor([0.9594, 0.3548, 0.9751, 0.5854, 0.6431, 0.8459, 0.8374, 0.4420, 0.2574,
        0.1708, 0.4292, 0.1682])
tensor([[0.9594],
        [0.3548],
        [0.9751],
        [0.5854],
        [0.6431],
        [0.8459],
        [0.8374],
        [0.4420],
        [0.2574],
        [0.1708],
        [0.4292],
        [0.1682]])
tensor([[0.9594, 0.3548, 0.9751, 0.5854, 0.6431, 0.8459, 0.8374, 0.4420, 0.2574,
         0.1708, 0.4292, 0.1682]])
tensor([[0.9594, 0.3548, 0.9751],
        [0.5854, 0.6431, 0.8459],
        [0.8374, 0.4420, 0.2574],
        [0.1708, 0.4292, 0.1682]])


In [15]:
# GPU
print(torch.cuda.is_available())
# if torch.cuda.is_available():
#   device = torch.device("cuda")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(3,2).to(device)
print(x)
x = x.to("cpu")
print(x)

True
tensor([[0.1159, 0.0656],
        [0.9751, 0.0762],
        [0.6860, 0.5650]], device='cuda:0')
tensor([[0.1159, 0.0656],
        [0.9751, 0.0762],
        [0.6860, 0.5650]])
